/** Tłumaczenia interfejsu widżetu konwersacyjnego (statyczne napisy). */

export interface ConvStrings {
  introDefault: string;
  nameLabel: string;
  namePlaceholder: string;
  emailLabel: string;
  emailPlaceholder: string;
  localhostCaptcha: string;
  start: string;
  done: string;
  question: (n: number) => string;
  restart: string;
  welcomeBack: (name: string) => string;
  preparing: string;
  multiHint: string;
  otherPlaceholder: string;
  answerPlaceholder: string;
  next: string;
  yourAnswers: string;
  summary: string;
  send: string;
  sending: string;
  thanks: (name: string) => string;
  sentInfo: string;
  errName: string;
  errEmail: string;
  errCaptcha: string;
  errGeneric: string;
  errConnection: string;
  errSend: string;
}

export const CONV_STRINGS: Record<string, ConvStrings> = {
  pl: {
    introDefault: "Zanim zaczniemy, zostaw swoje dane — odezwiemy się z odpowiedzią.",
    nameLabel: "Imię i nazwisko",
    namePlaceholder: "Jan Kowalski",
    emailLabel: "Adres e-mail",
    emailPlaceholder: "jan@przyklad.pl",
    localhostCaptcha: "Tryb localhost: weryfikacja reCAPTCHA pominięta (zadziała na produkcji).",
    start: "Rozpocznij",
    done: "Gotowe",
    question: (n) => `Pytanie ${n}`,
    restart: "Zacznij od nowa",
    welcomeBack: (name) => `Witaj ponownie, ${name}! Wróciliśmy do miejsca, w którym skończyłeś.`,
    preparing: "AI przygotowuje pytanie…",
    multiHint: "Możesz wybrać kilka odpowiedzi.",
    otherPlaceholder: "Coś nie pasuje albo chcesz dodać coś od siebie? Napisz tutaj…",
    answerPlaceholder: "Wpisz odpowiedź…",
    next: "Dalej",
    yourAnswers: "Twoje odpowiedzi",
    summary: "Streszczenie",
    send: "Zapisz i wyślij",
    sending: "Wysyłanie…",
    thanks: (name) => `Dziękujemy, ${name}!`,
    sentInfo: "Twoje odpowiedzi zostały wysłane.",
    errName: "Podaj imię i nazwisko.",
    errEmail: "Podaj poprawny adres e-mail.",
    errCaptcha: "Potwierdź, że nie jesteś robotem.",
    errGeneric: "Wystąpił błąd. Spróbuj ponownie.",
    errConnection: "Błąd połączenia. Sprawdź internet i spróbuj ponownie.",
    errSend: "Nie udało się wysłać. Spróbuj ponownie.",
  },
  de: {
    introDefault: "Bevor wir beginnen, hinterlassen Sie bitte Ihre Daten — wir melden uns mit einer Antwort.",
    nameLabel: "Vor- und Nachname",
    namePlaceholder: "Max Mustermann",
    emailLabel: "E-Mail-Adresse",
    emailPlaceholder: "max@beispiel.de",
    localhostCaptcha: "Localhost-Modus: reCAPTCHA übersprungen (funktioniert in der Produktion).",
    start: "Starten",
    done: "Fertig",
    question: (n) => `Frage ${n}`,
    restart: "Neu beginnen",
    welcomeBack: (name) => `Willkommen zurück, ${name}! Wir machen dort weiter, wo Sie aufgehört haben.`,
    preparing: "KI bereitet die Frage vor…",
    multiHint: "Sie können mehrere Antworten auswählen.",
    otherPlaceholder: "Passt nichts oder möchten Sie etwas hinzufügen? Schreiben Sie hier…",
    answerPlaceholder: "Antwort eingeben…",
    next: "Weiter",
    yourAnswers: "Ihre Antworten",
    summary: "Zusammenfassung",
    send: "Speichern und senden",
    sending: "Wird gesendet…",
    thanks: (name) => `Vielen Dank, ${name}!`,
    sentInfo: "Ihre Antworten wurden gesendet.",
    errName: "Bitte geben Sie Ihren Namen an.",
    errEmail: "Bitte geben Sie eine gültige E-Mail-Adresse an.",
    errCaptcha: "Bitte bestätigen Sie, dass Sie kein Roboter sind.",
    errGeneric: "Ein Fehler ist aufgetreten. Bitte erneut versuchen.",
    errConnection: "Verbindungsfehler. Bitte Internet prüfen und erneut versuchen.",
    errSend: "Senden fehlgeschlagen. Bitte erneut versuchen.",
  },
  en: {
    introDefault: "Before we start, please leave your details — we'll get back to you with an answer.",
    nameLabel: "Full name",
    namePlaceholder: "John Smith",
    emailLabel: "Email address",
    emailPlaceholder: "john@example.com",
    localhostCaptcha: "Localhost mode: reCAPTCHA skipped (works in production).",
    start: "Start",
    done: "Done",
    question: (n) => `Question ${n}`,
    restart: "Start over",
    welcomeBack: (name) => `Welcome back, ${name}! We picked up where you left off.`,
    preparing: "AI is preparing the question…",
    multiHint: "You can select several answers.",
    otherPlaceholder: "Nothing fits or want to add something? Write here…",
    answerPlaceholder: "Type your answer…",
    next: "Next",
    yourAnswers: "Your answers",
    summary: "Summary",
    send: "Save and send",
    sending: "Sending…",
    thanks: (name) => `Thank you, ${name}!`,
    sentInfo: "Your answers have been sent.",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email address.",
    errCaptcha: "Please confirm you are not a robot.",
    errGeneric: "Something went wrong. Please try again.",
    errConnection: "Connection error. Check your internet and try again.",
    errSend: "Could not send. Please try again.",
  },
  fr: {
    introDefault: "Avant de commencer, laissez vos coordonnées — nous reviendrons vers vous.",
    nameLabel: "Nom et prénom",
    namePlaceholder: "Jean Dupont",
    emailLabel: "Adresse e-mail",
    emailPlaceholder: "jean@exemple.fr",
    localhostCaptcha: "Mode localhost : reCAPTCHA ignoré (fonctionne en production).",
    start: "Commencer",
    done: "Terminé",
    question: (n) => `Question ${n}`,
    restart: "Recommencer",
    welcomeBack: (name) => `Bon retour, ${name} ! Nous reprenons là où vous vous étiez arrêté.`,
    preparing: "L'IA prépare la question…",
    multiHint: "Vous pouvez sélectionner plusieurs réponses.",
    otherPlaceholder: "Rien ne convient ou vous voulez ajouter quelque chose ? Écrivez ici…",
    answerPlaceholder: "Saisissez votre réponse…",
    next: "Suivant",
    yourAnswers: "Vos réponses",
    summary: "Résumé",
    send: "Enregistrer et envoyer",
    sending: "Envoi…",
    thanks: (name) => `Merci, ${name} !`,
    sentInfo: "Vos réponses ont été envoyées.",
    errName: "Veuillez indiquer votre nom.",
    errEmail: "Veuillez saisir une adresse e-mail valide.",
    errCaptcha: "Veuillez confirmer que vous n'êtes pas un robot.",
    errGeneric: "Une erreur s'est produite. Veuillez réessayer.",
    errConnection: "Erreur de connexion. Vérifiez votre Internet et réessayez.",
    errSend: "Échec de l'envoi. Veuillez réessayer.",
  },
  es: {
    introDefault: "Antes de empezar, deja tus datos — te responderemos.",
    nameLabel: "Nombre y apellidos",
    namePlaceholder: "Juan Pérez",
    emailLabel: "Correo electrónico",
    emailPlaceholder: "juan@ejemplo.es",
    localhostCaptcha: "Modo localhost: reCAPTCHA omitido (funciona en producción).",
    start: "Empezar",
    done: "Listo",
    question: (n) => `Pregunta ${n}`,
    restart: "Empezar de nuevo",
    welcomeBack: (name) => `¡Hola de nuevo, ${name}! Continuamos donde lo dejaste.`,
    preparing: "La IA está preparando la pregunta…",
    multiHint: "Puedes seleccionar varias respuestas.",
    otherPlaceholder: "¿Nada encaja o quieres añadir algo? Escribe aquí…",
    answerPlaceholder: "Escribe tu respuesta…",
    next: "Siguiente",
    yourAnswers: "Tus respuestas",
    summary: "Resumen",
    send: "Guardar y enviar",
    sending: "Enviando…",
    thanks: (name) => `¡Gracias, ${name}!`,
    sentInfo: "Tus respuestas han sido enviadas.",
    errName: "Introduce tu nombre.",
    errEmail: "Introduce un correo electrónico válido.",
    errCaptcha: "Confirma que no eres un robot.",
    errGeneric: "Se produjo un error. Inténtalo de nuevo.",
    errConnection: "Error de conexión. Comprueba tu Internet e inténtalo de nuevo.",
    errSend: "No se pudo enviar. Inténtalo de nuevo.",
  },
  it: {
    introDefault: "Prima di iniziare, lascia i tuoi dati — ti risponderemo.",
    nameLabel: "Nome e cognome",
    namePlaceholder: "Mario Rossi",
    emailLabel: "Indirizzo e-mail",
    emailPlaceholder: "mario@esempio.it",
    localhostCaptcha: "Modalità localhost: reCAPTCHA saltato (funziona in produzione).",
    start: "Inizia",
    done: "Fatto",
    question: (n) => `Domanda ${n}`,
    restart: "Ricomincia",
    welcomeBack: (name) => `Bentornato, ${name}! Riprendiamo da dove eri rimasto.`,
    preparing: "L'IA sta preparando la domanda…",
    multiHint: "Puoi selezionare più risposte.",
    otherPlaceholder: "Niente va bene o vuoi aggiungere qualcosa? Scrivi qui…",
    answerPlaceholder: "Scrivi la tua risposta…",
    next: "Avanti",
    yourAnswers: "Le tue risposte",
    summary: "Riepilogo",
    send: "Salva e invia",
    sending: "Invio in corso…",
    thanks: (name) => `Grazie, ${name}!`,
    sentInfo: "Le tue risposte sono state inviate.",
    errName: "Inserisci il tuo nome.",
    errEmail: "Inserisci un indirizzo e-mail valido.",
    errCaptcha: "Conferma di non essere un robot.",
    errGeneric: "Si è verificato un errore. Riprova.",
    errConnection: "Errore di connessione. Controlla la rete e riprova.",
    errSend: "Invio non riuscito. Riprova.",
  },
};
